In [1]:
pip install numpy

In [3]:
!pip install numpy

In [7]:
# import
import numpy as np

In [9]:
data = np.random.rand(2, 3, 4)
zeroes = np.zeros((2, 2, 2))
full = np.full((2, 2, 2), 7)
ones = np.ones((2, 2, 2))

In [11]:
data

array([[[0.24869916, 0.11146275, 0.57893533, 0.88204557],
        [0.13964848, 0.34769891, 0.47972875, 0.72569904],
        [0.31674558, 0.32915289, 0.33006246, 0.55700589]],

       [[0.99190994, 0.36132791, 0.03716274, 0.52587692],
        [0.46604432, 0.89928814, 0.75408954, 0.8611978 ],
        [0.88152428, 0.81354588, 0.01916607, 0.04266891]]])

In [13]:
zeroes

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [15]:
full

array([[[7, 7],
        [7, 7]],

       [[7, 7],
        [7, 7]]])

In [17]:
ones

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [19]:
arr = np.array([[1, 2, 3, 4], [1, 2, 3, 4]])

In [21]:
arr

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [23]:
type(arr)

numpy.ndarray

In [27]:
#Attributes to read specific properties of numpy
shape = data.shape
size = data.size
types = data.dtype

In [29]:
shape

(2, 3, 4)

In [31]:
size

24

In [33]:
types

dtype('float64')

In [35]:
#Slicing
arr = data[0]
slicer = data[0][0:2]
reverse = data[-1]
singleval = data[0][0][0]

In [37]:
arr

array([[0.24869916, 0.11146275, 0.57893533, 0.88204557],
       [0.13964848, 0.34769891, 0.47972875, 0.72569904],
       [0.31674558, 0.32915289, 0.33006246, 0.55700589]])

In [39]:
slicer

array([[0.24869916, 0.11146275, 0.57893533, 0.88204557],
       [0.13964848, 0.34769891, 0.47972875, 0.72569904]])

In [41]:
reverse

array([[0.99190994, 0.36132791, 0.03716274, 0.52587692],
       [0.46604432, 0.89928814, 0.75408954, 0.8611978 ],
       [0.88152428, 0.81354588, 0.01916607, 0.04266891]])

In [43]:
singleval

0.2486991619491521

In [45]:
data

array([[[0.24869916, 0.11146275, 0.57893533, 0.88204557],
        [0.13964848, 0.34769891, 0.47972875, 0.72569904],
        [0.31674558, 0.32915289, 0.33006246, 0.55700589]],

       [[0.99190994, 0.36132791, 0.03716274, 0.52587692],
        [0.46604432, 0.89928814, 0.75408954, 0.8611978 ],
        [0.88152428, 0.81354588, 0.01916607, 0.04266891]]])

In [47]:
#Update
list1 = np.random.rand(10)
list2 = np.random.rand(10)

In [49]:
list1

array([0.62848639, 0.3942802 , 0.57849285, 0.51997774, 0.11543635,
       0.73934097, 0.43249082, 0.47263912, 0.21510366, 0.07089914])

In [51]:
list2

array([0.18348499, 0.82630385, 0.65631401, 0.53391348, 0.35028188,
       0.34452041, 0.80607863, 0.00950503, 0.30721021, 0.48515993])

In [53]:
#Basic Math
add = np.add(list1, list2)
sub = np.subtract(list1, list2)
div = np.divide(list1, list2)
mult = np.multiply(list1, list2)
dot = np.dot(list1, list2)

In [67]:
#add
#sub
# div
#mult
dot

1.847155985644711

In [69]:
#Stat Functions
sqrt = np.sqrt(25)
ab = np.abs(-2)
power = np.power(2, 7)
log = np.log(25)
exp = np.exp([2, 3])
mins = np.min(list1)
max = np.max(list1)

In [85]:
exp

array([ 7.3890561 , 20.08553692])

In [89]:
data[0][0][0] = 700
data

array([[[7.00000000e+02, 1.11462749e-01, 5.78935331e-01, 8.82045574e-01],
        [1.39648482e-01, 3.47698912e-01, 4.79728754e-01, 7.25699043e-01],
        [3.16745583e-01, 3.29152890e-01, 3.30062457e-01, 5.57005895e-01]],

       [[9.91909936e-01, 3.61327905e-01, 3.71627446e-02, 5.25876918e-01],
        [4.66044317e-01, 8.99288143e-01, 7.54089540e-01, 8.61197803e-01],
        [8.81524285e-01, 8.13545885e-01, 1.91660664e-02, 4.26689064e-02]]])

In [91]:
data.sort()
data

array([[[1.11462749e-01, 5.78935331e-01, 8.82045574e-01, 7.00000000e+02],
        [1.39648482e-01, 3.47698912e-01, 4.79728754e-01, 7.25699043e-01],
        [3.16745583e-01, 3.29152890e-01, 3.30062457e-01, 5.57005895e-01]],

       [[3.71627446e-02, 3.61327905e-01, 5.25876918e-01, 9.91909936e-01],
        [4.66044317e-01, 7.54089540e-01, 8.61197803e-01, 8.99288143e-01],
        [1.91660664e-02, 4.26689064e-02, 8.13545885e-01, 8.81524285e-01]]])

In [93]:
print(data.shape)

(2, 3, 4)


In [95]:
data = data.reshape(2, 2, -1)
data.shape

(2, 2, 6)

In [97]:
#Append and Insert
zeroes = np.zeros((8))
print(zeroes)
zeroes = np.append(zeroes, [3,4])
print(zeroes)

[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 3. 4.]


In [99]:
zeroes = np.insert(zeroes, 2, 1)
print(zeroes)

[0. 0. 1. 0. 0. 0. 0. 0. 0. 3. 4.]


In [101]:
#Delete
np.delete(data, 0, axis= 1)

array([[[0.47972875, 0.72569904, 0.31674558, 0.32915289, 0.33006246,
         0.55700589]],

       [[0.8611978 , 0.89928814, 0.01916607, 0.04266891, 0.81354588,
         0.88152428]]])

In [103]:
np.save("new array", data)

In [105]:
test = np.load("new array.npy")
test

array([[[1.11462749e-01, 5.78935331e-01, 8.82045574e-01, 7.00000000e+02,
         1.39648482e-01, 3.47698912e-01],
        [4.79728754e-01, 7.25699043e-01, 3.16745583e-01, 3.29152890e-01,
         3.30062457e-01, 5.57005895e-01]],

       [[3.71627446e-02, 3.61327905e-01, 5.25876918e-01, 9.91909936e-01,
         4.66044317e-01, 7.54089540e-01],
        [8.61197803e-01, 8.99288143e-01, 1.91660664e-02, 4.26689064e-02,
         8.13545885e-01, 8.81524285e-01]]])